name: Build

on:
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:

env:
  DOCKER_RUN: docker run --rm -v $GITHUB_WORKSPACE/output:/data/output -v $(pwd)/tests:/data/tests -v $GITHUB_WORKSPACE/samples:/data/protos protocpolyglot/protoc-polyglot

jobs:
  build_and_test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup a version
      run: echo "Tag=$(date +%s)" >> $GITHUB_ENV
    - name: Build the base Docker image
      run: docker build -t protocpolyglot/protoc-polyglot:$Tag -f docker/protoc-polyglot-x64.dockerfile .
    - name: Build the server Docker image # This should be a separate job, but we do not upload the base image
      run: docker build -t protoc-polyglot-server-x64:$Tag --build-arg base_image_tag=$Tag -f docker/protoc-polyglot-server-x64.dockerfile .
    - name: Tag docker image
      run: docker tag protocpolyglot/protoc-polyglot:$Tag protocpolyglot/protoc-polyglot
    - name: Test single service python
      run: eval "$DOCKER_RUN --languages python --service-yml /data/protos/services.yml"
    - name: Test protoc command
      run: eval "bash $GITHUB_WORKSPACE/tests/run.sh"
    - name: Output check
      run: |
        ls
        pwd
        echo $GITHUB_WORKSPACE
        ls output/python/bookclub
        ls output/js

#  build_server:
#    runs-on: ubuntu-22.04
#
#    needs: build_base
#
#    steps:
#    - uses: actions/checkout@v3
#    - name: Build the server Docker image
#      run: docker build -t protoc-polyglot-server-x64:$(date +%s) --build-arg base_image_tag=$(date +%s) -f docker/protoc-polyglot-server-x64.dockerfile .
  
